server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  file-storage: #文件存储配置
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    minio: # MinIO，由于 MinIO SDK 支持 AWS S3，其它兼容 AWS S3 协议的存储平台也都可配置在这里
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: "admin"
        secret-key: "admin123"
        bucket-name: "photo"
        end-point: "http://192.168.111.128:9000"
        domain: "http://192.168.111.128:9000/photo/" # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: "" # 基础路径
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learningPlat
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    #knife4j配置
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件大小
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      #mybatis-plus日志打印
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


