server:
  port: 8080
spring:
  file-storage: #文件存储配置
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    minio: # MinIO，由于 MinIO SDK 支持 AWS S3，其它兼容 AWS S3 协议的存储平台也都可配置在这里
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: "admin"
        secret-key: "admin123"
        bucket-name: "photo"
        end-point: "http://192.168.111.128:9000"
        domain: "http://192.168.111.128:9000/photo/" # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: "" # 基础路径
  #    local-plus: # 本地存储升级版，不使用的情况下可以不写
  #      - platform: local-plus-1 # 存储平台标识
  #        enable-storage: true  #启用存储
  #        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
  #        domain: "D:/Temp/" # 访问域名，例如：“http://127.0.0.1:8030/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
  #        base-path: local-plus/ # 基础路径
  #        path-patterns: /** # 访问路径
  #        storage-path: D:/Temp/ # 存储路径
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learningPlat
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    #knife4j配置
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件大小
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      #mybatis-plus日志打印
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


